
CREATE TABLE ESTADIO (
    ID         INT          PRIMARY KEY AUTO_INCREMENT,
    NOME       VARCHAR(255) NOT NULL,
    LOCALIZACAO VARCHAR(255) NOT NULL,
    CAPACIDADE INT          NOT NULL
);

CREATE TABLE PAIS (
    ID         INT          PRIMARY KEY AUTO_INCREMENT,
    NOME       VARCHAR(255) NOT NULL,
    SIGLA      VARCHAR(255) NOT NULL,
    CONTINENTE VARCHAR(255) NOT NULL
);

CREATE TABLE TECNICO (
    ID      INT          PRIMARY KEY AUTO_INCREMENT,
    NOME    VARCHAR(255) NOT NULL,
    FK_PAIS INT          NOT NULL,
    FOREIGN KEY (FK_PAIS) REFERENCES PAIS(ID)
);

CREATE TABLE SELECAO (
    ID          INT        PRIMARY KEY AUTO_INCREMENT,
    NOME        VARCHAR(255) NOT NULL,
    SIGLA       VARCHAR(5)   NOT NULL,
    GRUPO       VARCHAR(1)   NOT NULL,
    FK_PAIS     INT          NOT NULL,
    FK_TECNICO  INT          NOT NULL,
    FOREIGN KEY (FK_PAIS)    REFERENCES PAIS(ID),
    FOREIGN KEY (FK_TECNICO) REFERENCES TECNICO(ID)
);

CREATE TABLE FASE (
    ID   INT          PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE PARTIDA (
    ID           INT      PRIMARY KEY AUTO_INCREMENT,
    FK_ESTADIO   INT      NOT NULL,
    DATA_HORA    DATETIME NOT NULL,
    FK_SELECAO1  INT      NOT NULL,
    FK_SELECAO2  INT      NOT NULL,
    FK_FASE      INT      NOT NULL,
    FOREIGN KEY (FK_ESTADIO)  REFERENCES ESTADIO(ID),
    FOREIGN KEY (FK_SELECAO1) REFERENCES SELECAO(ID),
    FOREIGN KEY (FK_SELECAO2) REFERENCES SELECAO(ID),
    FOREIGN KEY (FK_FASE)     REFERENCES FASE(ID)
);

CREATE TABLE FUNCAO (
    ID   INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE JOGADOR (
    ID            INT          PRIMARY KEY AUTO_INCREMENT,
    NOME          VARCHAR(255) NOT NULL,
    NOME_CAMISA   VARCHAR(255) NOT NULL,
    NUMERO_CAMISA INT          NOT NULL,
    FK_SELECAO    INT          NOT NULL,
    FK_PAIS       INT          NOT NULL,
    FK_FUNCAO     INT          NOT NULL,
    FOREIGN KEY (FK_SELECAO) REFERENCES SELECAO(ID),
    FOREIGN KEY (FK_PAIS)    REFERENCES PAIS(ID),
    FOREIGN KEY (FK_FUNCAO)  REFERENCES FUNCAO(ID)
);


CREATE TABLE GOL_PARTIDA (
    ID                 INT      PRIMARY KEY AUTO_INCREMENT,
    FK_JOGADOR         INT      NOT NULL,
    FK_PARTIDA         INT      NOT NULL,
    MINUTO             INT    NOT NULL,
    FK_SELECAO_PONTUOU INT      NOT NULL,
    FOREIGN KEY (FK_JOGADOR)         REFERENCES JOGADOR(ID),
    FOREIGN KEY (FK_PARTIDA)         REFERENCES PARTIDA(ID),
    FOREIGN KEY (FK_SELECAO_PONTUOU) REFERENCES SELECAO(ID)
);

CREATE TABLE RESULTADO_PARTIDA (
    ID          INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RESULTADO   ENUM('E', 'VS1', 'VS2'),
    FK_SELECAO1 INT NOT NULL,
    FK_SELECAO2 INT NOT NULL,
    FOREIGN KEY (FK_SELECAO1) REFERENCES SELECAO(ID),
    FOREIGN KEY (FK_SELECAO2) REFERENCES SELECAO(ID)
);
