CREATE TABLE TORCEDOR(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    IDADE INT NOT NULL,
    IDENTIFICADOR_PESSOAL VARCHAR(255) NOT NULL UNIQUE
    
);

CREATE TABLE ESTADIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    LOCALIZACAO VARCHAR(255) NOT NULL,
    CAPACIDADE INT NOT NULL
);
CREATE TABLE PAIS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    SIGLA VARCHAR(255) NOT NULL,
    CONTINENTE VARCHAR(255) NOT NULL
    
);
CREATE TABLE TECNICO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    FK_PAIS INT NOT NULL,
    FOREIGN KEY(FK_PAIS) REFERENCES PAIS(ID)
);
CREATE TABLE SELECAO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    SIGLA VARCHAR(5) NOT NULL,
    FK_PAIS INT NOT NULL,
    FK_TECNICO INT NOT NULL,
    FOREIGN KEY (FK_PAIS) REFERENCES PAIS(ID),
    FOREIGN KEY (FK_TECNICO) REFERENCES TECNICO(ID)
);
CREATE TABLE FASE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
);
CREATE TABLE PARTIDA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_ESTADIO INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    FK_SELECAO1 INT NOT NULL,
    FK_SELECAO2 INT NOT NULL,
    FK_FASE INT NOT NULL,
    FOREIGN KEY (FK_ESTADIO) REFERENCES ESTADIO(ID),
    FOREIGN KEY (FK_SELECAO1) REFERENCES SELECAO(ID),
    FOREIGN KEY (FK_SELECAO2) REFERENCES SELECAO(ID),
    FOREIGN KEY (FK_FASE) REFERENCES FASE(ID)
);
CREATE TABLE INGRESSO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_TORCEDOR INT NOT NULL,
    FK_JOGO INT NOT NULL,
    FOREIGN KEY (FK_TORCEDOR) REFERENCES TORCEDOR(ID),
    FOREIGN KEY (FK_JOGO) REFERENCES PARTIDA(ID)
);

CREATE TABLE GOL_PARTIDA{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGADOR INT NOT NULL,
    FK_PARTIDA INT NOT NULL,
    MINUTO TIME NOT NULL,
    FK_SELECAO_PONTUOU INT NOT NULL,
    FOREIGN KEY(FK_JOGADOR) REFERENCE JOGADOR(ID),
    FOREIGN KEY(FK_PARTIDA) REFERENCE PARTIDA(ID),
    FOREIGN KEY(FK_SELECAO_PONTUOU) REFERENCESS SELECAO(ID)
};

CREATE TABLE SUBSTIUICAO {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGADOR_ENTRA INT NOT NULL,
    FK_ JOGADOR_SAI INT NOT NULL,
    FK_PARTIDA INT NOT NULL,
    MINUTO TIME NOT NULL,
    FOREIGN KEY (FK_JOGADOR_ENTRA) REFERENCES JOGADOR(ID),
    FOREIGN KEY (FK_JOGADOR_SAI) REFERENCES JOGADOR(ID),
    FOREIGN KEY (FK_PARTIDA) RERENCES PARTIDA(ID)

};

CRAETE TABLE FALTA {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_PARTIDA INT NOT NULL,
    FK_JOGADOR_SOFREU INT NOT NULL,
    FK_JOGADOR_FEZ INT NOT NULL,
    CARTÃO ENUM('V', 'A'),
    MINUTO TIME NOT NULL,
    FOREIGN KEY(FK_PARTIDA) REFERENCES PARTIDA(ID),
    FOREIGN KEY (FK_JOGADOR_SOFREU) REFERENCES JOGADOR(ID),
    FOREIGN KEY (FK_JOGADOR_FEZ) REFERENCES JOGADOR(ID)
};

CREATE TABLE PENALT {
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGADOR_COBRANDO INT NOT NULL,
    FK_PARTIDA INT NOT NULL,
    MINUTO TIME NOT NULL,
    RESULTADO ENUM('GOL', 'DEFENDIDO') NOT NULL,
    FK_GOL INT ,
    FOREIGN KEY(FK_JOGADOR_COBRANDO) REFERENCES JOGADOR(ID),
    FOREIGN KEY(FK_PARTIDA) REFERENCES PARTIDA(ID),
    FOREIGN KEY (FK_GOL) REFERENCES GOL_PARTIDA(ID)
};

CREATE TABLE FUNCAO{
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL
};

CREATE TABLE JOGADOR{
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    NOME_CAMISA INT NOT NULL,
    NUMERO_CAMISA INT NOT NULL,
    FK_SELECAO INT NOT NULL,
    FK_PAIS INT NOT NULL,
    FK_FUNCAO INT NOT NULL,
    FOREIGN KEY(FK_SELECAO) REFERENCES SELECAO(ID),
    FOREIGN KEY(FK_PAIS) REFERENCES PAIS(ID),
    FOREIGN KEY(FK_FUNCAO) REFERENCES FUNCAO(ID)
};

CREATE TABLE ARBITRO{
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    FK_PAIS INT NOT NULL,
    FOREIGN KEY(FK_PAIS) REFERENCES PAIS(ID)

};

CREATE TABLE ARBITRO_PARTIDA{
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    FK_ARBITRO INT NOT NULL,
    FK_PARTIDA INT NOT NULL,
    FK_FUNÇÃO INT NOT NULL,
    FOREIGN KEY(FK_ARBITRO) REFERENCES ARBITRO(ID),
    FOREIGN KEY(FK_PARTIDA) REFERENCES PARTIDA(ID),
    FOREIGN KEY(FK_FUNÇÃO) REFERENCES FUNCAO(ID)
};

CREATE TABLE RESULTADO_PARTIDA{
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RESULTADO ENUM('E', 'VS1', 'VS2'),
    FK_SELECAO1 INT NOT NULL,
    FK_SELECAO2 INT NOT NULL,
    FOREIGN KEY(FK_SELECAO1) REFERENCES SELECAO(ID),
    FOREIGN KEY(FK_SELECAO2) REFERENCES SELECAO(ID)
};
