
SELECT 
    s.NOME AS Selecao,
    j.NOME AS Jogador
FROM JOGADOR j
INNER JOIN SELECAO s ON j.FK_SELECAO = s.ID
ORDER BY s.NOME, j.NOME;

SELECT 
    E.NOME AS ESTADIO,
    P.DATA_HORA AS PARTIDA
FROM ESTADIO E
INNER JOIN PARTIDA P ON P.FK_ESTADIO  = E.ID
ORDER BY E.ID, P.FK_ESTADIO;

