SELECT 
	s.id as ID,
    s.NOME AS SELECAO,
    j.NOME AS JOGADOR,
    j.NUMERO_CAMISA,
    f.NOME AS POSICAO
FROM JOGADOR j
INNER JOIN SELECAO s ON j.FK_SELECAO = s.ID
INNER JOIN FUNCAO f ON j.FK_FUNCAO = f.ID
ORDER BY s.NOME;

SELECT 
    E.NOME AS ESTADIO,
    P.DATA_HORA AS PARTIDA
FROM ESTADIO E
INNER JOIN PARTIDA P ON P.FK_ESTADIO  = E.ID
ORDER BY E.ID, P.FK_ESTADIO;

SELECT 
    p.ID,
    s1.NOME AS SELECAO_CASA,
    s2.NOME AS SELECAO_FORA,
    e.NOME AS ESTADIO,
    p.DATA_HORA
FROM PARTIDA p
INNER JOIN SELECAO s1 ON p.FK_SELECAO1 = s1.ID
INNER JOIN SELECAO s2 ON p.FK_SELECAO2 = s2.ID
INNER JOIN ESTADIO e ON p.FK_ESTADIO = e.ID
WHERE s1.NOME = 'Brasil' OR s2.NOME = 'Brasil';

SELECT 
    p.ID AS PARTIDA,
    j.NOME AS JOGADOR,
    gp.MINUTO,
    s.NOME AS SELECAO
FROM GOL_PARTIDA gp
INNER JOIN PARTIDA p ON gp.FK_PARTIDA = p.ID
INNER JOIN JOGADOR j ON gp.FK_JOGADOR = j.ID
INNER JOIN SELECAO s ON gp.FK_SELECAO_PONTUOU = s.ID
ORDER BY p.ID, gp.MINUTO;

SELECT 
    p.ID AS PARTIDA,
    s1.NOME AS SELEÇÃO1,
    s2.NOME AS SELEÇÃO2,
    rp.RESULTADO
FROM PARTIDA p
INNER JOIN SELECAO s1 ON p.FK_SELECAO1 = s1.ID
INNER JOIN SELECAO s2 ON p.FK_SELECAO2 = s2.ID
INNER JOIN RESULTADO_PARTIDA rp ON rp.FK_SELECAO1 = s1.ID AND rp.FK_SELECAO2 = s2.ID;

SELECT 
    j.NOME AS JOGADOR,
    s.NOME AS SELECAO,
    COUNT(gp.ID) AS TOTAL_GOLS
FROM JOGADOR j
INNER JOIN SELECAO s ON j.FK_SELECAO = s.ID
INNER JOIN GOL_PARTIDA gp ON gp.FK_JOGADOR = j.ID
GROUP BY j.ID
ORDER BY TOTAL_GOLS DESC;

SELECT 
    COUNT(DISTINCT p.ID) AS TOTAL_PARTIDAS,
    COUNT(gp.ID) AS TOTAL_GOLS,
    COUNT(gp.ID) / COUNT(DISTINCT p.ID) AS MEDIA_GOLS
FROM PARTIDA p
LEFT JOIN GOL_PARTIDA gp ON p.ID = gp.FK_PARTIDA;

SELECT 
    s.GRUPO,
    s.NOME AS SELECAO
FROM SELECAO s
INNER JOIN PAIS p ON s.FK_PAIS = p.ID
ORDER BY s.GRUPO, s.NOME;

SELECT 
    s.NOME AS SELECAO,
    COUNT(gp.ID) AS GOLS_MARCADOS
FROM SELECAO s
LEFT JOIN GOL_PARTIDA gp ON gp.FK_SELECAO_PONTUOU = s.ID
GROUP BY s.ID
ORDER BY GOLS_MARCADOS DESC;
